### ISSUE TITLE
Gulp 4 Support

### ISSUE THREAD

**Issue by mikeerickson** [mbolaric/vscode-tasks-panel#3]
Trying to get this project to work with Gulp 4 tasks but not having much success.  

Should it support Gulp 4?

**Comment by mbolaric** [comment]
Yes this extension support Gulp 4, I use this extension in several project with gulp 4. In attachment is one simple project that on my computer work with gulp 4 (Ubuntu 18.04.1). Only issue that I see is if 'npm install' is running from VSCode terminal, VSCode must be restarted before extension can load tasks.

[gulp-project.zip](https://github.com/mbolaric/vscode-tasks-panel/files/2975523/gulp-project.zip)

**Comment by mikeerickson** [comment]
@mbolaric cool, I will have a look and see what differs
