### ISSUE TITLE
Task search for child directory

### ISSUE THREAD

**Issue by tiansin** [mbolaric/vscode-tasks-panel#5]
Add tasks can be searched from the sub-directory. Thank you.

**Comment by steveoliveira** [comment]
Is this already complete? where can i get the vscode extension of version 0.2.0? thank you and good work

**Comment by Mordef** [comment]
Maybe thats why i become this?
```
The grunt task definition file is not found.
The gulp task definition file is not found.
```
gulpfile.js and node_modules is in subfolder
