### ISSUE TITLE
Unable to find gulp tasks in gulpfile.js

### ISSUE THREAD

**Issue by blachawk** [mbolaric/vscode-tasks-panel#7]
I apologize in advance if I am overlooking something, but after installing this extension in Visual Studio Code (verision 1.41.1), the task panel displays, but it cannot find my gulp tasks located within my gulpfile.js file (on the root).

My tasks within my js file look like this...

```js
gulp.task('build', gulp.series('build-css'));
gulp.task('rebuild', gulp.series('clean','build'));

gulp.task('build-beautify', gulp.series('build-css-beautify'));
gulp.task('rebuild-beautify', gulp.series('clean','build-beautify'));
```

Is there a setting I need to enable, in order for these tasks to my listed?

**Comment by mbolaric** [comment]
No, all need to work automatic, only `node_modules` must exists (`npm install `must be run before extension can read tasks.).
